# Generated by Django 5.2.3 on 2025-06-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Ressource')),
                ('nom', models.CharField(max_length=200)),
                ('descriptif', models.TextField(blank=True)),
                ('coefficient', models.FloatField()),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='ues.ue')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['ue', 'code'],
            },
        ),
    ]
