# Generated by Django 5.2.3 on 2025-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code UE')),
                ('nom', models.CharField(max_length=200)),
                ('semestre', models.PositiveIntegerField()),
                ('credits_ects', models.PositiveIntegerField(verbose_name='Crédits ECTS')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['semestre', 'code'],
            },
        ),
    ]
