# Generated by Django 5.2.3 on 2025-06-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(verbose_name='Note sur 20')),
                ('appreciation', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='examens.examen')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['examen', 'etudiant__nom'],
                'unique_together': {('examen', 'etudiant')},
            },
        ),
    ]
